### ISSUE TITLE
Mod is not updated for tModLoader v0.10.1

### ISSUE THREAD

**Issue by Vergial** [Jofairden/EvenMoreModifiers#2]
Actual error message is as follows.

-------------------------------------

It looks like this mod doesn't have a class extending Mod. Mods need a Mod class to function.
   at Terraria.ModLoader.AssemblyManager.InstantiateMods(List`1 modsToLoad)

Inner Exception:
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Terraria.ModLoader.AssemblyManager.InstantiateMods(List`1 modsToLoad)

**Comment by Jofairden** [comment]
This mod is due to be re-released.
